use mydb;
INSERT INTO Ingrediente(nome, status) VALUES ('abóbora japonesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abóbora moranga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abobrinha menina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacaxi havaí', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacaxi pérola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abricó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('absinto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açaí', true);
INSERT INTO Ingrediente(nome, status) VALUES ('acafrão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('acém', true);
INSERT INTO Ingrediente(nome, status) VALUES ('acelga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('acerola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('achocolatado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar cristal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar de confeiteiro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar mascavo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar orgânico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar refinado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('adoçante', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ágar-ágar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('agrião', true);
INSERT INTO Ingrediente(nome, status) VALUES ('água', true);
INSERT INTO Ingrediente(nome, status) VALUES ('água de coco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('água tônica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aguardente', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aguê', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aipim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aipo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alcaparras', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alcatra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alcatra com maminha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alcachofra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alecrim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface americana', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface crespa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface frisada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface lisa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface roxa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alfafa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alheira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alho-poró', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aliche', true);
INSERT INTO Ingrediente(nome, status) VALUES ('almeirão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amaciante de carnes', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amarula', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ameixa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ameixa preta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ameixa seca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amendoim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amêndoa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amido de milho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('amora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('anchova', true);
INSERT INTO Ingrediente(nome, status) VALUES ('anis-estrelado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('apreseuntado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz arbóreo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz integral', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz japonês', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz negro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz parboilizado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz selvagem', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz vermelho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aspargo branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aspargo verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('asinha de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('atum', true);
INSERT INTO Ingrediente(nome, status) VALUES ('aveia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('avelã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('avocado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeite', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeite de dendê', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeitona verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeitona roxa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('babaçu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('baby beef', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bacon', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bacalhau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('badejo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bagre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('baguete', true);
INSERT INTO Ingrediente(nome, status) VALUES ('baiacu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana-da-terra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana-maçã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana-nanica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana-passa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana-prata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('barriga suína', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata asterix', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata-baroa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata-doce branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata-doce roxa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata frita', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata inglesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata palha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('baunilha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bebida de soja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('berinjela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('beterraba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bicarbonato de sódio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('biscoito', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisnaguinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca com filé', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca de carneiro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca sem filé', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca suína', true);
INSERT INTO Ingrediente(nome, status) VALUES ('blanquet', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bolacha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bourboun', true);
INSERT INTO Ingrediente(nome, status) VALUES ('brócolis', true);
INSERT INTO Ingrediente(nome, status) VALUES ('broto de bambu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('broto de feijão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cacau em pó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cachaça', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cação', true);
INSERT INTO Ingrediente(nome, status) VALUES ('café', true);
INSERT INTO Ingrediente(nome, status) VALUES ('café solúvel', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cajá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caju', true);
INSERT INTO Ingrediente(nome, status) VALUES ('calda de caramelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('calda de chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('calda de morango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caldo de carne', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caldo de costela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caldo de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caldo de legume', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão branco pequeno', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão pequeno', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão pistola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão rosa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cana de açúcar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canela em pau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canela em pó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canjica amarela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canjica branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cará', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carambola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cardamomo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carpa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carapau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caqui chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caqui fuji', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caqui fuyu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('capuccino', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caranguejo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carne de avestruz', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carne de soja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('carne seca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('castanha de caju', true);
INSERT INTO Ingrediente(nome, status) VALUES ('castanha-do-pará', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caviar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cupim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('capa de filé', true);
INSERT INTO Ingrediente(nome, status) VALUES ('capeletti', true);
INSERT INTO Ingrediente(nome, status) VALUES ('catchup', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cebola branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cebola roxa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cebolinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cenoura', true);
INSERT INTO Ingrediente(nome, status) VALUES ('centeio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cereja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cerveja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cevada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá de boldo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá de camomila', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá de capim cidreira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá de erva cidreira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá mate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá preto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('champagne', true);
INSERT INTO Ingrediente(nome, status) VALUES ('champignon', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chantily', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chicória', true);
INSERT INTO Ingrediente(nome, status) VALUES ('charque', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chicharro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chimichurri', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate amargo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate ao leite', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate de soja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate meio amargo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('choupa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chouriço', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chuchu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chucrute', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ciabatta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cidra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('clara de ovo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('club soda', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coalhada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cominho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('conchiglione', true);
INSERT INTO Ingrediente(nome, status) VALUES ('conhaque', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coco ralado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coco verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coentro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cogumelo-de-paris', true);
INSERT INTO Ingrediente(nome, status) VALUES ('colorau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('confete de chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('contra filé', true);
INSERT INTO Ingrediente(nome, status) VALUES ('copa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('copa suína', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coração de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('corvina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('costela minga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('costela ripa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxa com sobrecoxa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxa de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxa de pato', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxão duro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxão mole', true);
INSERT INTO Ingrediente(nome, status) VALUES ('coxinha da asa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('couve-flor', true);
INSERT INTO Ingrediente(nome, status) VALUES ('couve manteiga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('couve-rábano', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cranberry', true);
INSERT INTO Ingrediente(nome, status) VALUES ('creme de avelã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('creme de cebola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cream cheese', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cream cracker', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cravo-da-índia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('creme de leite', true);
INSERT INTO Ingrediente(nome, status) VALUES ('croissant', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cupim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cupuaçu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('curaçau blue', true);
INSERT INTO Ingrediente(nome, status) VALUES ('curimba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('curry', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cúcurma', true);
INSERT INTO Ingrediente(nome, status) VALUES ('damasco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('doce de leite', true);
INSERT INTO Ingrediente(nome, status) VALUES ('dourado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('energético', true);
INSERT INTO Ingrediente(nome, status) VALUES ('erva-cidreira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('erva doce', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ervas finas', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ervilha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('escargot', true);
INSERT INTO Ingrediente(nome, status) VALUES ('escarola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('espinafre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('espumante', true);
INSERT INTO Ingrediente(nome, status) VALUES ('essência de baunilha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('estragão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('extrato de tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fagotini', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha de centeio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha de mandioca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha de milho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha de rosca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha de trigo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha láctea', true);
INSERT INTO Ingrediente(nome, status) VALUES ('farinha panko', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fava de baunilha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fécula de batata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão amarelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão azuki', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão carioca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão de corda', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão fradinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão preto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fermento biológico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fermento biológio fresco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fermento químico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fermento em pó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('filé argentino', true);
INSERT INTO Ingrediente(nome, status) VALUES ('filé mignon', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fígado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('figo roxo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('figo verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fios de ovos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('flocos de arroz', true);
INSERT INTO Ingrediente(nome, status) VALUES ('flocos de aveia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('flor de sal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('folha de louro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fraldinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('framboesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('frango defumado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('frango à passarinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fruta do conde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fruta-pão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('fubá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('funghi secchi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('furikake', true);
INSERT INTO Ingrediente(nome, status) VALUES ('garoupa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina incolor', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de abacaxi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de amora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de cereja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de framboesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de maracujá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de morango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de tutti-fruti', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gelatina de uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de abacaxi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de amora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de damasco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de figo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de framboesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de frutas vermelhas', true); 
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de gengibre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de goiaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de mirtilo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de morango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de pimenta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('géleia de uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gema de ovo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gengibre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gergelim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gersal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('gim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('glicose de milho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('goiaba branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('goiaba vermelha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('grão-de-bico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('granola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('granulado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('graviola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('grumixama', true);
INSERT INTO Ingrediente(nome, status) VALUES ('guaraná', true);
INSERT INTO Ingrediente(nome, status) VALUES ('guariroba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('hibisco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('hiratake', true);
INSERT INTO Ingrediente(nome, status) VALUES ('hondashi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('hortelã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('inhame', true);
INSERT INTO Ingrediente(nome, status) VALUES ('iogurte', true);
INSERT INTO Ingrediente(nome, status) VALUES ('iogurte natural', true);
INSERT INTO Ingrediente(nome, status) VALUES ('isotônico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('jabuticaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('jaca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('jambo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('jiló', true);
INSERT INTO Ingrediente(nome, status) VALUES ('joelho de porco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('kani-kama', true);
INSERT INTO Ingrediente(nome, status) VALUES ('kiwi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('kobe beef', true);
INSERT INTO Ingrediente(nome, status) VALUES ('konnyaku', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lámen', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lagarto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lagosta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('laranja bahia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('laranja lima', true);
INSERT INTO Ingrediente(nome, status) VALUES ('laranja pêra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('leite', true);
INSERT INTO Ingrediente(nome, status) VALUES ('leite condensado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('leite de coco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('leite em pó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('leite fermentado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lemon pepper', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lentilha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lichia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('licor de abricó', true);
INSERT INTO Ingrediente(nome, status) VALUES ('licor de chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('licor de maracujá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão galego', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão rosa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão siciliano', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão taiti', true);
INSERT INTO Ingrediente(nome, status) VALUES ('língua de boi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linguiça calabresa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linguça de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linguiça de pernil', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linguiça toscana', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linhaça', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lombo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lombo de bacalhau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lombo suíno', true);
INSERT INTO Ingrediente(nome, status) VALUES ('linguado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('lula', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã argentina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã fuji', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã gala', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macadâmia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão alfabeto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão argola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão bifum', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão boca de leão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão cabelo de anjo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão caramujinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão caracolino', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão espaguete', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão furadinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão gravata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão instâtaneo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão ninho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão nhoque', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão parafuso', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão parppadelle', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão pena', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão tortilhone', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão yakissoba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macaxeira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maionese', true);
INSERT INTO Ingrediente(nome, status) VALUES ('malzbier', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mamão formosa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mamão havaí', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mamão papaia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maminha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mandioca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mandioquinha salsa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga espada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga palmer', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga rosa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga tommy', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mangaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manjericão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manjerona', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manteiga com sal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manteiga sem sal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maracujá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('margarina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('marisco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('marmelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('marsmallow', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa folhada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa para lasanha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa para panqueca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa para pastel', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa para pizza', true);
INSERT INTO Ingrediente(nome, status) VALUES ('massa podre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maxixe', true);
INSERT INTO Ingrediente(nome, status) VALUES ('menta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mel', true);
INSERT INTO Ingrediente(nome, status) VALUES ('merluza', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mexerica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mexilhão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('milho verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mingau', true);
INSERT INTO Ingrediente(nome, status) VALUES ('miolo de alcatra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('missô', true);
INSERT INTO Ingrediente(nome, status) VALUES ('moela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mortedela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('molho inglês', true);
INSERT INTO Ingrediente(nome, status) VALUES ('molho shoyu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('molho tarê', true);
INSERT INTO Ingrediente(nome, status) VALUES ('moluscos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melancia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melancia amarela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melancia baby', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melão orange', true);
INSERT INTO Ingrediente(nome, status) VALUES ('melão pele de sapo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('molho de tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('molho tártaro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('morango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('morcela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mostarda', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mostarda dijon', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mirtilo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('músculo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mussarela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mussarela búfala', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nabo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('namorado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nectarina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nêspera', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nhoque', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nori', true);
INSERT INTO Ingrediente(nome, status) VALUES ('noz-moscada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('nozes', true);
INSERT INTO Ingrediente(nome, status) VALUES ('óleo de canola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('óleo de coco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('óleo de gergelim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('óleo de girassol', true);
INSERT INTO Ingrediente(nome, status) VALUES ('óleo de soja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('orégano', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ostras', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ovos brancos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ovos de codorna', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ovos vermelhos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pacú', true);
INSERT INTO Ingrediente(nome, status) VALUES ('paio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('paleta bovina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('paleta cordeira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('paleta suína', true);
INSERT INTO Ingrediente(nome, status) VALUES ('palmito', true);
INSERT INTO Ingrediente(nome, status) VALUES ('palmito pupunha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão australiano', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de aveia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de batata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de crioche', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de centeio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de forma', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de linhaça', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão de ló', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão francês', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão italiano', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão preto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão sírio', true);
INSERT INTO Ingrediente(nome, status) VALUES ('páprica doce', true);
INSERT INTO Ingrediente(nome, status) VALUES ('páprica picante', true);
INSERT INTO Ingrediente(nome, status) VALUES ('patinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('peito de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('portobello', true);
INSERT INTO Ingrediente(nome, status) VALUES ('peito de peru', true);
INSERT INTO Ingrediente(nome, status) VALUES ('peixe-espada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pepino caipira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pepino japonês', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pepperoni', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pêra portuguesa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pêra williams', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pernil', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pequi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pescado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pêssego', true);
INSERT INTO Ingrediente(nome, status) VALUES ('piapará', true);
INSERT INTO Ingrediente(nome, status) VALUES ('picanha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('picanha suína', true);
INSERT INTO Ingrediente(nome, status) VALUES ('picles', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimentão amarelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimentão verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimentão vermelho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pinhão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pistache', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pitaia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta-caiena', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta calabresa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta cambuci', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta chipotle', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta dedo-de-moça', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta-da-jamaica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta-de-biquinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta-de-cheiro', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta do reino branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta do reino branca em grãos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta do reino preta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta do reino preta em grãos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta rosa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta habanero', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta jalapeño', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta-malagueta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta tabasco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pintado', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pipoca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pirarucu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pitanga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('polpa de tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('polvilho azedo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('polvilho doce', true);
INSERT INTO Ingrediente(nome, status) VALUES ('polvo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('poncã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ponta de agulha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('portobello', true);
INSERT INTO Ingrediente(nome, status) VALUES ('posta branca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('posta vermelha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('presunto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('presunto de parma', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pururuca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo briê', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo de cabra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo cheddar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo coalho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo cottage', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo gorgonzola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo emmental', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo estepe', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo gouda', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo gruyère', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo mascarpone', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo mussarela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo minas', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo parmesão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo prato', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo provolone', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo suiço', true);
INSERT INTO Ingrediente(nome, status) VALUES ('quiabo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('quirera', true);
INSERT INTO Ingrediente(nome, status) VALUES ('quinoa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('rabanete', true);
INSERT INTO Ingrediente(nome, status) VALUES ('raíz de bardana', true);
INSERT INTO Ingrediente(nome, status) VALUES ('rabo de boi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ravioli', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante de cola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante de guaraná', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante de laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante de limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante de uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('repolho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('repolho roxo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('requeijão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('ricota', true);
INSERT INTO Ingrediente(nome, status) VALUES ('robalo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('romã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('rúcula', true);
INSERT INTO Ingrediente(nome, status) VALUES ('rum', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sal', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sal grosso', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sal do himalaia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sal marinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salame', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salmão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salsa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salsão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salsicha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('salsinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sálvia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('saquê', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sardinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('semente de abóbora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('semente de girassol', true);
INSERT INTO Ingrediente(nome, status) VALUES ('shimeji', true);
INSERT INTO Ingrediente(nome, status) VALUES ('shiitake', true);
INSERT INTO Ingrediente(nome, status) VALUES ('siri', true);
INSERT INTO Ingrediente(nome, status) VALUES ('siriguela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sobrecoxa de frango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sobrecoxa de pato', true);
INSERT INTO Ingrediente(nome, status) VALUES ('soja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sopa de cebola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sorvete', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sour cream', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de abacaxi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de abacaxi com hortelã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de amora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de acerola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de acerola com laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de cajá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de caju', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de cupuaçu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de clorofila', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de frutas vermelhas', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de goiaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de graviola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de mamão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de mamão com laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de maracujá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de melancia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de melão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de morango', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de pêssego', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de pitanga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco de uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco verde', true);
INSERT INTO Ingrediente(nome, status) VALUES ('sucrilhos', true);
INSERT INTO Ingrediente(nome, status) VALUES ('t-bone', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tahine', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tainha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('talharim', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tâmara', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tamarindo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tambaqui', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tamboril', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tangerina', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tapioca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tender', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tequila', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tilápia', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tofu', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate cereja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate longa vida', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate seco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomilho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('torrada', true);
INSERT INTO Ingrediente(nome, status) VALUES ('torresmo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('toucinho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('traíra', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tremoço', true);
INSERT INTO Ingrediente(nome, status) VALUES ('trigo para quibe', true);
INSERT INTO Ingrediente(nome, status) VALUES ('trufas', true);
INSERT INTO Ingrediente(nome, status) VALUES ('truta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tucunaré', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uísque', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva niagara', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva passa', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva rubi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva thompson', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vagem', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vermouth', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vieira', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre balsâmico', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre de álcool', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre de limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre de maçã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre de vinho tinto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho branco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho do porto', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho rosé', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho tinto doce', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho tinto seco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vodka', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vôngole', true);
INSERT INTO Ingrediente(nome, status) VALUES ('waffle', true);
INSERT INTO Ingrediente(nome, status) VALUES ('wasabi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('whisky', true);
INSERT INTO Ingrediente(nome, status) VALUES ('xarope de bordo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('zaatar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('zimbro', true);

INSERT INTO Ingrediente(nome, status) VALUES ('abóbora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abobrinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacaxi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeitona', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canjica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caqui', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cebola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cogumelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('figo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('goiaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mamão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('milho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pepino', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo ', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo camembert', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho', true);