use mydb;
delete from Ingrediente where id=567;
INSERT INTO Ingrediente(nome, status) VALUES ('abóbora', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abobrinha', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('abacaxi', true);
INSERT INTO Ingrediente(nome, status) VALUES ('açúcar', true);
INSERT INTO Ingrediente(nome, status) VALUES ('alface', true);
INSERT INTO Ingrediente(nome, status) VALUES ('arroz', true);
INSERT INTO Ingrediente(nome, status) VALUES ('azeitona', true);
INSERT INTO Ingrediente(nome, status) VALUES ('banana', true);
INSERT INTO Ingrediente(nome, status) VALUES ('batata', true);
INSERT INTO Ingrediente(nome, status) VALUES ('bisteca', true);
INSERT INTO Ingrediente(nome, status) VALUES ('camarão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canela', true);
INSERT INTO Ingrediente(nome, status) VALUES ('canjica', true);
INSERT INTO Ingrediente(nome, status) VALUES ('caqui', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cebola', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chá', true);
INSERT INTO Ingrediente(nome, status) VALUES ('chocolate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('cogumelo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('feijão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('figo', true);
INSERT INTO Ingrediente(nome, status) VALUES ('goiaba', true);
INSERT INTO Ingrediente(nome, status) VALUES ('laranja', true);
INSERT INTO Ingrediente(nome, status) VALUES ('limão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('maçã', true);
INSERT INTO Ingrediente(nome, status) VALUES ('macarrão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('mamão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('manga', true);
INSERT INTO Ingrediente(nome, status) VALUES ('milho', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pão', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pepino', true);
INSERT INTO Ingrediente(nome, status) VALUES ('pimenta', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo ', true);
INSERT INTO Ingrediente(nome, status) VALUES ('queijo camembert', true);
INSERT INTO Ingrediente(nome, status) VALUES ('refrigerante', true);
INSERT INTO Ingrediente(nome, status) VALUES ('suco', true);
INSERT INTO Ingrediente(nome, status) VALUES ('tomate', true);
INSERT INTO Ingrediente(nome, status) VALUES ('uva', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinagre', true);
INSERT INTO Ingrediente(nome, status) VALUES ('vinho', true);
