-- MySQL Script generated by MySQL Workbench
-- Qui 07 Abr 2016 22:11:01 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `admin` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Receita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Receita` (
  `idReceita` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `modoPreparo` VARCHAR(45) NULL,
  `rendimento` VARCHAR(45) NULL,
  `tempoPreparo` VARCHAR(45) NULL,
  `dificuldade` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  `idUsuario` INT NOT NULL,
  `imagem` LONGBLOB NULL,
  PRIMARY KEY (`idReceita`),
  INDEX `fk_Receita_Usuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Receita_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingrediente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingrediente` (
  `idIngrediente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemReceita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itemReceita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itemReceita` (
  `idItem` INT NOT NULL,
  `quantidade` INT(11) NULL,
  `unidadeMedida` VARCHAR(45) NULL,
  `idReceita` INT NOT NULL,
  `idIngrediente` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_itemReceita_Receita1_idx` (`idReceita` ASC),
  INDEX `fk_itemReceita_Ingrediente1_idx` (`idIngrediente` ASC),
  CONSTRAINT `fk_itemReceita_Receita1`
    FOREIGN KEY (`idReceita`)
    REFERENCES `mydb`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemReceita_Ingrediente1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `mydb`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL,
  `texto` VARCHAR(45) NULL,
  `dataComentario` DATETIME NULL,
  `idReceita` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Receita1_idx` (`idReceita` ASC),
  INDEX `fk_Comentario_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Comentario_Receita1`
    FOREIGN KEY (`idReceita`)
    REFERENCES `mydb`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `idTag` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TagReceita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TagReceita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TagReceita` (
  `idTags` INT NOT NULL,
  `idReceita` INT NOT NULL,
  `idTag` INT NOT NULL,
  PRIMARY KEY (`idTags`),
  INDEX `fk_TagReceita_Receita1_idx` (`idReceita` ASC),
  INDEX `fk_TagReceita_Tag1_idx` (`idTag` ASC),
  CONSTRAINT `fk_TagReceita_Receita1`
    FOREIGN KEY (`idReceita`)
    REFERENCES `mydb`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TagReceita_Tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `mydb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SugestaoReceita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SugestaoReceita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SugestaoReceita` (
  `idSugestaoReceita` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSugestaoReceita`),
  INDEX `fk_SugestaoReceita_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_SugestaoReceita_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemSugestao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itemSugestao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itemSugestao` (
  `idIngrediente` INT NOT NULL,
  `idSugestaoReceita` INT NOT NULL,
  INDEX `fk_itemSugestao_Ingrediente1_idx` (`idIngrediente` ASC),
  INDEX `fk_itemSugestao_SugestaoReceita1_idx` (`idSugestaoReceita` ASC),
  CONSTRAINT `fk_itemSugestao_Ingrediente1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `mydb`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemSugestao_SugestaoReceita1`
    FOREIGN KEY (`idSugestaoReceita`)
    REFERENCES `mydb`.`SugestaoReceita` (`idSugestaoReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Qualificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Qualificacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Qualificacao` (
  `idReceita` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nota` VARCHAR(45) NULL,
  PRIMARY KEY (`idReceita`, `idUsuario`),
  INDEX `fk_Receita_has_Usuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Receita_has_Usuario_Receita1_idx` (`idReceita` ASC),
  CONSTRAINT `fk_Receita_has_Usuario_Receita1`
    FOREIGN KEY (`idReceita`)
    REFERENCES `mydb`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receita_has_Usuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
